name: inventoryplatform
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  loading_indicator: ^3.1.1
  sidebarx: ^0.17.1
  fl_chart: ^0.69.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  mobile_scanner: ^6.0.2
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  pdf: ^3.11.3
  file_picker: ^9.2.3
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  ulid: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.5
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/images/AppLogo-1024x1024.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/AppLogoWeb-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/images/JustLogoInventarioSplash-1024x1024.png" 
  android: true 
  ios: true 
  web: true
  fullscreen: true 

  android_12:
    icon_background_color: "#FFFFFF"
    image: "assets/images/JustLogoInventarioSplash-1024x1024.png" 
    icon_background_color_dark: "#1a1a1a"
    image_dark: "assets/images/JustLogoInventarioSplash-1024x1024.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/