// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-DGCJrVBy1szpKtW9-R4aQ8y8UuLd_w',
    appId: '1:1010918109842:web:f7db86d83fe88d8d4bec4b',
    messagingSenderId: '1010918109842',
    projectId: 'inventoryplatform-3a2ae',
    authDomain: 'inventoryplatform-3a2ae.firebaseapp.com',
    storageBucket: 'inventoryplatform-3a2ae.firebasestorage.app',
    measurementId: 'G-SWY7DXKNCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrr_lS9lyEkxjL8LgTMDWzt750njsJ1iM',
    appId: '1:1010918109842:android:057abd900cc328854bec4b',
    messagingSenderId: '1010918109842',
    projectId: 'inventoryplatform-3a2ae',
    storageBucket: 'inventoryplatform-3a2ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6BPam8TZ560x6PZko85-2Z5U722HVIU',
    appId: '1:1010918109842:ios:a2224e725b6f8fbe4bec4b',
    messagingSenderId: '1010918109842',
    projectId: 'inventoryplatform-3a2ae',
    storageBucket: 'inventoryplatform-3a2ae.firebasestorage.app',
    androidClientId: '1010918109842-e3gf5ne91iule4r1caik3jg831j7uju6.apps.googleusercontent.com',
    iosClientId: '1010918109842-0g4i60h19uh8u401npbi1ll55s7ave2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd6BPam8TZ560x6PZko85-2Z5U722HVIU',
    appId: '1:1010918109842:ios:a2224e725b6f8fbe4bec4b',
    messagingSenderId: '1010918109842',
    projectId: 'inventoryplatform-3a2ae',
    storageBucket: 'inventoryplatform-3a2ae.firebasestorage.app',
    androidClientId: '1010918109842-e3gf5ne91iule4r1caik3jg831j7uju6.apps.googleusercontent.com',
    iosClientId: '1010918109842-0g4i60h19uh8u401npbi1ll55s7ave2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-DGCJrVBy1szpKtW9-R4aQ8y8UuLd_w',
    appId: '1:1010918109842:web:c4d70dc67011027b4bec4b',
    messagingSenderId: '1010918109842',
    projectId: 'inventoryplatform-3a2ae',
    authDomain: 'inventoryplatform-3a2ae.firebaseapp.com',
    storageBucket: 'inventoryplatform-3a2ae.firebasestorage.app',
    measurementId: 'G-8TKXF86512',
  );

}